provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

sources:
  - ingress

domainFilters:
  - whiteforge.ai

policy: upsert-only

txtOwnerId: external-dns

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
