# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.opentelemetryCollector.create }}
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{.Release.Namespace}}
  annotations:
    {{- if .Values.opentelemetryCollector.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.opentelemetryCollector.irsaRoleArn | quote }}
    {{- end }}
    {{- if not .Values.serviceAccounts.annotationsOnlyForCartservice }}
    {{- with .Values.serviceAccounts.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.opentelemetryCollector.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    extensions:
      sigv4auth:
        region: {{ .Values.opentelemetryCollector.awsRegion | quote }}
        service: "aps"
      sigv4auth/xray:
        region: {{ .Values.opentelemetryCollector.awsRegion | quote }}
        service: "xray"

    exporters:
      prometheusremotewrite:
        endpoint: {{ .Values.opentelemetryCollector.ampEndpoint | quote }}
        auth:
          authenticator: sigv4auth
        resource_to_telemetry_conversion:
          enabled: true
      awsxray:
        region: {{ .Values.opentelemetryCollector.awsRegion | quote }}
      debug:
        verbosity: basic

    connectors:
      spanmetrics:

    service:
      extensions: [sigv4auth, sigv4auth/xray]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [awsxray, spanmetrics, debug]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: []
          exporters: [prometheusremotewrite, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.opentelemetryCollector.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.opentelemetryCollector.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.opentelemetryCollector.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      {{- if .Values.securityContext.enable }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      {{- end }}
      containers:
      - name: otel-gateway
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        args:
        - --config=/conf/otel-collector-config.yaml
        image: otel/opentelemetry-collector-contrib:0.144.0@sha256:213886eb6407af91b87fa47551c3632be1a6419ff3a5114ef1e6fc364628496f
        volumeMounts:
        - name: otel-collector-config
          mountPath: /conf
      volumes:
      - name: otel-collector-config
        configMap:
          name: {{ .Values.opentelemetryCollector.name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: self-metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: {{ .Values.opentelemetryCollector.name }}
  type: ClusterIP
{{- if .Values.networkPolicies.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.opentelemetryCollector.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.adService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.cartService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.checkoutService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.currencyService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.emailService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.frontend.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.loadGenerator.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.paymentService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.productCatalogService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.recommendationService.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.shippingService.name }}
    ports:
     - port: 4317
       protocol: TCP
  egress:
  - {}
{{- end }}
{{- if .Values.sidecars.create }}
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  workloadSelector:
    labels:
      app: {{ .Values.opentelemetryCollector.name }}
  egress:
  - hosts:
    - istio-system/*
{{- end }}
{{- if .Values.authorizationPolicies.create }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.opentelemetryCollector.name }}
  rules:
  - from:
    - source:
        principals:
        {{- if .Values.serviceAccounts.create }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.adService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.cartService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.checkoutService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.currencyService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.emailService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.frontend.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.loadGenerator.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.paymentService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.productCatalogService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.recommendationService.name }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.shippingService.name }}
        {{- else }}
        - cluster.local/ns/{{ .Release.Namespace }}/sa/default
        {{- end }}
    to:
    - operation:
        ports:
        - "4317"
{{- end }}
{{- end }}